version: '3.7'
services:
  db:
    image: 'mysql'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MAINDB_NAME}
    ports:
      - 3306:3306
    volumes:
      - cs492c:/var/lib/mysql
    container_name: fedev-mysql-server
    command: --default-authentication-plugin=mysql_native_password

  cs492c-api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    volumes:
      - ./src:/home/node/app/src
      - ./client:/home/node/app/client
    container_name: cs492c-api-server
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - db
    entrypoint:
      - /home/node/app/entrypoint.sh

volumes:
  cs492c:
